=== github-pratik/SDL-final-/3XML_Validate/school.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="schools">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="school" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="rollno" type="xs:string" />
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="branch" type="xs:string" />
                            <xs:element name="credits" type="xs:integer" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== github-pratik/SDL-final-/3XML_Validate/school.xml
<?xml version="1.0" encoding="UTF-8"?>
<school xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="school.xsd">
    <school>
        <rollno>001</rollno>
        <name>John Doe</name>
        <branch>IT</branch>
        <credits>100000</credits>
    </school>
    <school>
        <rollno>002</rollno>
        <name>Jane Smith</name>
        <branch>CS</branch>
        <credits>90000</credits>
    </school>
</school>
